#Microservice authentication-server Configurations

#O que for configurado nessa área vale para todos os perfis de start de aplicação.
#Utilizo essa área para incluir as configurações para o ambiente de desenvolvimento (sem perfil definido)

server:
  port: 8080
  contextPath: /uaa

spring:
  jpa:
    database-platform: MYSQL
  jdbc:
    driverClassName: ${microservices.series.mysqldb.driverClassName}
    url: ${microservices.series.mysqldb.url}
    user: ${microservices.series.mysqldb.user}
    pass: ${microservices.series.mysqldb.pass}

  mail:
    host: smtp.sendgrid.net
    port: 587
    username: microservices
    password: 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

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

---

spring:
  profiles: staging  

# O que for configurado nessa área pode sobrescrever ou adicionar propriedades para os perfis de ambientes de testes

---

spring:
  profiles: production

# O que for configurado nessa área pode sobrescrever ou adicionar propriedades para os perfis de ambientes de produçào
