#Microservice authentication-server Configurations

#O que for configurado nessa área vale para todos os perfis de start de aplicação.
#Utilizo essa área para incluir as configurações para o ambiente de desenvolvimento (sem perfil definido)

server:
  port: 8080
  contextPath: /uaa

spring:
  jpa:
    database-platform: MYSQL
  jdbc:
    driverClassName: ${microservices.series.mysqldb.driverClassName}
    url: ${microservices.series.mysqldb.url}
    user: ${microservices.series.mysqldb.user}
    pass: ${microservices.series.mysqldb.pass}

  mail:
    host: smtp.gmail.com
    port: 587

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

microservices.series.authentication-server:
  redirecturl: http://localhost:3000
  url: http://localhost:8080/uaa

---

spring:
  profiles: staging  

# O que for configurado nessa área pode sobrescrever ou adicionar propriedades para os perfis de ambientes de testes

---

spring:
  profiles: production

# O que for configurado nessa área pode sobrescrever ou adicionar propriedades para os perfis de ambientes de produçào
